branches:
  only:
    - master
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libgmp-dev
    - libmpfr-dev
    - ccache
# command to install dependencies
cache:
cache:
  apt
  directories:
    - $HOME/.pip-cache/
install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - nosetests --with-coverage
after_success:
  coveralls
