branches:
  only:
    - master
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
cache:
  apt
  pip
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
# Install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coveralls

# Run tests
script:
  - nosetests --with-coverage --cov-config .coveragerc

# Calculate coverage
after_success:
  coveralls --config_file .coveragerc
